### ISSUE TITLE
Multiple date color based on recent modify date

### ISSUE THREAD

**Issue by Jimmy-JS** [eza-community/eza-themes#5]
How to set multiple color based on recent modify date just like in the readme?
![CleanShot 2024-11-18 at 14 24 55](https://github.com/user-attachments/assets/7c8bd80d-9274-4432-bebf-8a2e45085e92)

Like to make the more recent modified file to have lighter color and darker for the older one. Since I don't see this in the theme yml

**Comment by 0xDEAD-C0DE** [comment]
@Jimmy-JS This is not a theme issue. This is done by `eza --color-scale=age`
